### ISSUE TITLE
"Fatal error occurred"

### ISSUE THREAD

**Issue by runofthemill** [sdobreff/vscode-php-resolver#1]
Hi there!

I'm excited to see a new extension that might be better than the existing ones :P

After installing the extension and opening a PHP file, I get a `phpcs Fatal error occurred` notification, and looking at the extension output I see this:

```
["INFO" - 4:41:36 PM] Switched to new file - starting code sniffer
["INFO" - 4:41:36 PM] phpcs - Dispose diagnostic collection
["INFO" - 4:41:36 PM] phpcs - The document URI file:///<some_redacted_path>/src/Bootstrap.php
["INFO" - 4:41:36 PM] phpcs - Extracting standards from the configuration
["INFO" - 4:41:36 PM] phpcs - Spawning the command with parameters - -q - --report=json --standard=
["INFO" - 4:41:36 PM] phpcs - Writing the extracted file content to the stdin
["INFO" - 4:41:36 PM] phpcs - No data received - exit
["INFO" - 4:41:36 PM] phpcs - Collecting the output finished starting parsing
["ERROR" - 4:41:36 PM] phpcs - Failed collecting proper output - Unexpected end of JSON input
["INFO" - 4:41:36 PM] phpcs - Received - 
```

As soon as I updated the paths to `phpcs` and `phpcbf` in the extension settings the error went away, so the "problem" is more like "the error message didn't accurately indicate what's wrong".

Seems like this could be resolved in a few ways:
- don't pre-populate the path for `phpResolver.phpSnifferCommand` and force the user to configure it before it does anything
- check that the executable exists/add a message if it doesn't
- default to checking for a global `phpcs` or `./vendor/bin/phpcs`
- some combination of the above

Cheers!

**Comment by sdobreff** [comment]
Ha! Good one @runofthemill - Thank you very much, will take care of that.
Glad that you like the extension.
