### ISSUE TITLE
How can I use my project's phpcs.xml file?

### ISSUE THREAD

**Issue by nebulousGirl** [sdobreff/vscode-php-resolver#4]
Is there a way to automatically use the phpcs.xml file inside the current workspace?

Currently, I have to edit the settings manually if I change to a project that does not use the same standard.

**Comment by sdobreff** [comment]
I'm afraid this is currently not supported (because of the resources it will use).
Correct - you need to change the setting at the project level.
This will be implemented as there were other requests for this functionality.

Apologizes for the inconvenience

**Comment by sdobreff** [comment]
As of v.2.2 you can use phpResolver.phpCustomStandardsFile setting (default is phpcs.xml) to set custom rules file. The extension will traverse the directory structure (starting with the dir where the currently opened PHP file is located) and search upwards.

**Comment by madcoda9000** [comment]
I need this too :-(. When will be 2.2 released? Currently i am using 2.1.5 and my phpcs.xml is not recognized.

Best Regards

**Comment by sdobreff** [comment]
Current version is 2.2 - you should see it in your Visual Studio Code, it was released about 9 months ago.

**Comment by madcoda9000** [comment]
Hmm, that's intresting. My VS-Code do not provide that version:

![image](https://github.com/sdobreff/vscode-php-resolver/assets/25504739/774795d0-bf34-490f-bd41-d4c5184872a7)
